import type { Metadata } from "next";
import { Inter, MuseoModerno } from "next/font/google";

// imports
import Navbar from "@/app/_components/Navbar/Navbar";
import { ThemeProvider } from "@/components/shared/theme-provider";
import "./globals.css";
import AuthModal from "@/components/modals/auth-modal";
import CollegeName from "@/components/modals/college-name-modal";
import { Toaster } from "@/components/ui/sonner";
import { getUserSession } from "@/app/actions";
import HouseName from "@/components/modals/house-name-modal";

const inter = Inter({ subsets: ["latin"] });
const museoModerno = MuseoModerno({
  subsets: ["latin"],
  variable: "--font-museo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserSession();

  return (
    <html lang="en">
      <body className={`${inter.className} ${museoModerno?.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <main>
            <Navbar user={user!} />
            <Toaster />
            <AuthModal />
            <CollegeName />
            <HouseName />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
